model:
  nc: 3
  n_features: 512
  hidden_size: 256
  transformation:
    name: spin
    k: 6
  feature_extraction:
    name: vgg11
  sequence_modeling:
    name: transformer
    dropout: 0.1
    n_heads: 8
    d_model: 512
    d_ff: 2048
    n_layers: 6
  prediction:
    name: transformer

train:
  lr: 1.0
  grad_clip: 5.0
  # Adadelta optimizer
  optimizer: adadelta
  rho: 0.95
  eps: 0.00000001
  lr_milestones: [20000, 75000, 150000]
  lr_gamma: 0.1
  size_average: True
  reduce_loss: False

device: cuda
batch_max_length: 9
character: abcdefghklmnpstuvxyrz0123456789
imgH: 32
imgW: 100
rgb: True
sensitive: False
pad: False